/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.mysql.mysql.connector.java)
    api(libs.taglibs.standard)
    api(libs.org.apache.taglibs.taglibs.standard.jstlel)
    api(libs.org.apache.taglibs.taglibs.standard.spec)
    api(libs.javax.servlet.jsp.jstl.jstl.api)
    api(libs.com.sun.mail.javax.mail)
    api(libs.org.apache.tomcat.tomcat.util)
    api(libs.com.google.code.gson.gson)
    api(libs.org.javafxdata.datafx.datareader)
    api(libs.com.ip2location.ip2location.io.java)
    api(libs.com.ip2location.ip2location.java)
    api(libs.org.apache.poi.poi)
    api(libs.org.apache.poi.poi.ooxml.schemas)
    api(libs.org.apache.poi.poi.ooxml)
    api(libs.org.apache.logging.log4j.log4j.core)
    api(libs.org.apache.xmlbeans.xmlbeans)
    api(libs.org.apache.poi.openxml4j)
    api(libs.com.maxmind.geoip2.geoip2)
    api(libs.org.json.json)
    api(libs.com.zaxxer.hikaricp)
    api(libs.org.slf4j.slf4j.api)
    api(libs.io.jsonwebtoken.jjwt)
    api(libs.commons.io.commons.io)
    api(libs.commons.fileupload.commons.fileupload)
    api(libs.net.coobird.thumbnailator)
    api(libs.org.apache.commons.commons.lang3)
    api(libs.org.apache.httpcomponents.fluent.hc)
    api(libs.com.google.api.client.google.api.client)
    api(libs.com.google.http.client.google.http.client)
    api(libs.com.google.apis.google.api.services.oauth2)
    api(libs.com.google.apis.google.api.services.plus)
    api(libs.org.webjars.lru.cache)
    api(libs.org.webjars.npm.lru)
    api(libs.org.webjars.npm.lru.cache)
    api(libs.org.mvnpm.lru.cache)
    api(libs.org.webjars.chartjs)
    api(libs.org.hibernate.hibernate.core)
    api(libs.org.hibernate.orm.hibernate.core)
    api(libs.org.antlr.antlr)
    api(libs.dom4j.dom4j)
    api(libs.fr.myprysm.vertx.vertx.json)
    api(libs.com.googlecode.json.simple.json.simple)
    api(libs.javax.json.javax.json.api)
    api(libs.org.glassfish.javax.json)
    api(libs.commons.logging.commons.logging)
    api(libs.commons.codec.commons.codec)
    api(libs.org.apache.httpcomponents.httpclient)
    runtimeOnly(libs.org.apache.taglibs.taglibs.standard.impl)
    testImplementation(libs.junit.junit)
    providedCompile(libs.javax.servlet.jsp.jstl.javax.servlet.jsp.jstl.api)
    providedCompile(libs.javax.servlet.javax.servlet.api)
    providedCompile(libs.javax.servlet.servlet.api)
    providedCompile(libs.org.apache.directory.studio.jars)
}

group = "org.example"
version = "1.0-SNAPSHOT"
description = "BookStore Maven Webapp"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
